//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int OutcomeId { get; set; }
        public Nullable<int> PremiseId { get; set; }
        public Nullable<System.DateTime> ActionDateTime { get; set; }
        public Nullable<bool> DoorKnocked { get; set; }
        public string DoorKnockedCancelReason { get; set; }
        public Nullable<bool> ContactMade { get; set; }
        public string ContactMadeCancelReason { get; set; }
        public Nullable<bool> DecisionMakerMet { get; set; }
        public string DecisionMakerMetCancelReason { get; set; }
        public Nullable<bool> DecisionMakerPresentedTo { get; set; }
        public string DecisionMakerPresentedToCancelReason { get; set; }
        public Nullable<bool> Sale { get; set; }
        public string SaleCancelReason { get; set; }
        public Nullable<int> SalesRepId { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.DateTime> ArchivedDateTime { get; set; }
        public Nullable<bool> Reschedule { get; set; }
        public Nullable<System.DateTime> RescheduleDateTime { get; set; }
        public string ActionStageEnd { get; set; }
        public string ActionStageCancelReason { get; set; }
        public Nullable<bool> SaleKeypad { get; set; }
        public Nullable<bool> SaleBillPay { get; set; }
        public Nullable<bool> DoNotContact { get; set; }
        public string SaleOrigin { get; set; }
    }
}
