//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GISMultipleAllocationEntities : DbContext
    {
        public GISMultipleAllocationEntities()
            : base("name=GISMultipleAllocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepArea> RepAreas { get; set; }
        public virtual DbSet<SalesRep> SalesReps { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
    
        public virtual ObjectResult<PremisesByPremiseID_Result> PremisesByPremiseID(Nullable<int> premiseID)
        {
            var premiseIDParameter = premiseID.HasValue ?
                new ObjectParameter("PremiseID", premiseID) :
                new ObjectParameter("PremiseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesByPremiseID_Result>("PremisesByPremiseID", premiseIDParameter);
        }
    
        public virtual ObjectResult<PremisesByPremiseIdMostRecentOutcome_Result> PremisesByPremiseIdMostRecentOutcome(Nullable<int> premiseID)
        {
            var premiseIDParameter = premiseID.HasValue ?
                new ObjectParameter("PremiseID", premiseID) :
                new ObjectParameter("PremiseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesByPremiseIdMostRecentOutcome_Result>("PremisesByPremiseIdMostRecentOutcome", premiseIDParameter);
        }
    
        public virtual ObjectResult<PremisesBySalesRepIdCountKnockedByDate_Result> PremisesBySalesRepIdCountKnockedByDate(Nullable<int> salesRepId, Nullable<System.DateTime> checkDate)
        {
            var salesRepIdParameter = salesRepId.HasValue ?
                new ObjectParameter("salesRepId", salesRepId) :
                new ObjectParameter("salesRepId", typeof(int));
    
            var checkDateParameter = checkDate.HasValue ?
                new ObjectParameter("checkDate", checkDate) :
                new ObjectParameter("checkDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesBySalesRepIdCountKnockedByDate_Result>("PremisesBySalesRepIdCountKnockedByDate", salesRepIdParameter, checkDateParameter);
        }
    
        public virtual ObjectResult<PremisesBySalesRepIdMostRecentOutcomeCallBack_Result> PremisesBySalesRepIdMostRecentOutcomeCallBack(Nullable<int> salesRepId)
        {
            var salesRepIdParameter = salesRepId.HasValue ?
                new ObjectParameter("salesRepId", salesRepId) :
                new ObjectParameter("salesRepId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesBySalesRepIdMostRecentOutcomeCallBack_Result>("PremisesBySalesRepIdMostRecentOutcomeCallBack", salesRepIdParameter);
        }
    
        public virtual ObjectResult<PremisesBySalesRepIdMostRecentOutcomeCurrentArea_Result> PremisesBySalesRepIdMostRecentOutcomeCurrentArea(Nullable<int> salesRepId)
        {
            var salesRepIdParameter = salesRepId.HasValue ?
                new ObjectParameter("salesRepId", salesRepId) :
                new ObjectParameter("salesRepId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesBySalesRepIdMostRecentOutcomeCurrentArea_Result>("PremisesBySalesRepIdMostRecentOutcomeCurrentArea", salesRepIdParameter);
        }
    
        public virtual ObjectResult<PremisesBySalesRepIdMostRecentOutcomeRemoveKnocked_Result> PremisesBySalesRepIdMostRecentOutcomeRemoveKnocked(Nullable<int> salesRepId)
        {
            var salesRepIdParameter = salesRepId.HasValue ?
                new ObjectParameter("salesRepId", salesRepId) :
                new ObjectParameter("salesRepId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PremisesBySalesRepIdMostRecentOutcomeRemoveKnocked_Result>("PremisesBySalesRepIdMostRecentOutcomeRemoveKnocked", salesRepIdParameter);
        }
    
        public virtual ObjectResult<RepAreaPremisesAllocatedToSalesRepIdByDate_Result> RepAreaPremisesAllocatedToSalesRepIdByDate(Nullable<int> salesrepid, Nullable<System.DateTime> reportDate)
        {
            var salesrepidParameter = salesrepid.HasValue ?
                new ObjectParameter("salesrepid", salesrepid) :
                new ObjectParameter("salesrepid", typeof(int));
    
            var reportDateParameter = reportDate.HasValue ?
                new ObjectParameter("reportDate", reportDate) :
                new ObjectParameter("reportDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepAreaPremisesAllocatedToSalesRepIdByDate_Result>("RepAreaPremisesAllocatedToSalesRepIdByDate", salesrepidParameter, reportDateParameter);
        }
    }
}
