//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postcode
    {
        public int PostcodeID { get; set; }
        public string FullPostcode { get; set; }
        public bool InUse { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int Easting { get; set; }
        public int Northing { get; set; }
        public string GridReference { get; set; }
        public string Ward { get; set; }
        public string Parish { get; set; }
        public System.DateTime Introduced { get; set; }
        public Nullable<System.DateTime> Terminated { get; set; }
        public int Altitude { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Quality { get; set; }
        public string LSOACode { get; set; }
        public bool Processed { get; set; }
    }
}
