//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PostcodesEntities : DbContext
    {
        public PostcodesEntities()
            : base("name=PostcodesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PostalCode> PostalCodes { get; set; }
        public virtual DbSet<Postcode> Postcodes { get; set; }
        public virtual DbSet<Premis> Premises { get; set; }
    
        public virtual ObjectResult<Nullable<int>> CountKeypadPremisesByPostcode(string postcode)
        {
            var postcodeParameter = postcode != null ?
                new ObjectParameter("postcode", postcode) :
                new ObjectParameter("postcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountKeypadPremisesByPostcode", postcodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CountTotalPremisesByPostcode(string postcode)
        {
            var postcodeParameter = postcode != null ?
                new ObjectParameter("postcode", postcode) :
                new ObjectParameter("postcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountTotalPremisesByPostcode", postcodeParameter);
        }
    }
}
